services:
  - type: web
    name: cs2-microtwitter
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn group_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cs2-microtwitter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost"

databases:
  - name: cs2-microtwitter-db
    databaseName: cs2_microtwitter
    user: cs2_microtwitter_user