services:
  - type: web
    name: cs2-microtwitter
    runtime: docker
    repo: https://github.com/AlexandrKoteyko/group_project-dep.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cs2-microtwitter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: RENDER
        value: "true"

databases:
  - name: cs2-microtwitter-db
    databaseName: cs2_microtwitter
    user: cs2_microtwitter_user